### ISSUE TITLE
attempt to yield across metamethod/C-call boundary on iOS

### ISSUE THREAD

**Issue by dossy** [gamestdio/colyseus-defold#2] opened 2018-04-27 04:40 UTC
The example code works in the desktop simulator, but when executing the same code built and running on iOS, the following error is logged:

```
DEBUG:SCRIPT: ws://x.y.z.a:2657/?colyseusid=
DEBUG:SCRIPT: attempt to yield across metamethod/C-call boundary
```

Like I said, this code works perfectly -- I can join the room, send/receive messages, etc. -- when building and running in the desktop simulator from within the Defold editor, but when I bundle the game and run it on my actual iPhone 8, I get that error above.

I'm a Defold and Lua n00b.  What am I doing wrong, if anything?

**Comment by britzl** [comment] 2018-04-27 06:08
The problem you are facing is that on iOS we run a different version of Lua than on desktop. The two versions are almost 100% identical, but there are small small differences, one being that you may encounter problems with coroutines and protected function calls.

What you can try is this:

1. Download this file: https://github.com/keplerproject/coxpcall/blob/master/src/coxpcall.lua
2. Put it in your project and require it as early as possible in your application lifecycle.

This should make sure that pcall() and coroutines work well together.

**Comment by dossy** [comment] 2018-04-27 16:11
I added this to the top of my main game.script --

```
print "require modules.coxpcall"
require "modules.coxpcall"
```

And, the first things to output in the console when running the dev env:

```
INFO:DLIB: Flushing http cache to disk
INFO:ENGINE: Defold Engine 1.2.126 (32ba5ea)
INFO:ENGINE: Loading data from: http://10.6.113.160:49909/build
INFO:ENGINE: Initialised sound device 'default'

DEBUG:SCRIPT: require modules.coxpcall
```

Yet, I still get the error... do I need to do anything else?

**Comment by britzl** [comment] 2018-04-27 18:59
Hmm, I would have thought that would solve it. Ok, you need to provide a short number of steps to reproduce so that me or someone else (@endel ?) can investigate.

**Comment by dossy** [comment] 2018-04-27 21:12
1. New Project > From Template > Mobile game.

2. Add dependencies to `game.project`:

* https://github.com/gamestdio/colyseus-defold/archive/master.zip
* https://github.com/britzl/defold-websocket/archive/master.zip
* https://github.com/britzl/defold-luasocket/archive/master.zip
* https://github.com/subsoap/defold-luasec/archive/master.zip

3. Project > Fetch Libraries.

4. Get `coxpcall.lua`

    $ curl -sLO https://github.com/keplerproject/coxpcall/raw/master/src/coxpcall.lua

5. Replace `main.script` with the following:

```
require "coxpcall"

local ColyseusClient = require "colyseus.client"

local client

function init(self)
	msg.post(".", "acquire_input_focus")

	client = ColyseusClient.new("ws://10.6.113.160:2657")

	print("ColyseusClient.new")

	client:on('open', function()
		print("connected to Colyseus")
	end)
end

function update(self, dt)
     if client ~= nil then
         client:loop()
     end
end
```

6. Project > Build

Confirm that this builds and runs in the Local `dmengine`, which will result in the console containing something like this:

```
INFO:DLIB: Log server started on port 52635
INFO:ENGINE: Engine service started on port 52636
INFO:ENGINE: Defold Engine 1.2.126 (32ba5ea)
INFO:ENGINE: Loading data from: build/default
INFO:ENGINE: Initialised sound device 'default'

DEBUG:SCRIPT: ws://x.x.x.x:2657/?colyseusid=SJefJzxaG
DEBUG:SCRIPT: ColyseusClient.new
INFO:DLIB: SSDP: Started on address x.x.x.x
Registered luasec Extension
DEBUG:SCRIPT: connected to Colyseus
INFO:DLIB: SSDP: Done on address x.x.x.x
```

7. Project > Target > iPhone

8. Project > Build

Witness the error in the console:

```
INFO:ENGINE: Defold Engine 1.2.126 (32ba5ea)
INFO:ENGINE: Loading data from: http://x.x.x.x:50364/build
INFO:ENGINE: Initialised sound device 'default'

DEBUG:SCRIPT: ws://x.x.x.x:2657/?colyseusid=
DEBUG:SCRIPT: attempt to yield across metamethod/C-call boundary
DEBUG:SCRIPT: ColyseusClient.new
```

**Comment by dossy** [comment] 2018-04-28 16:01
@britzl - That's the minimal case to reproduce what I'm seeing.  Let me know if you're able to reproduce, and if not, let me know what other details I can provide.

Alternatively, if you can point me in the right neighborhood, I can try to come up with a fix.  Is there a way to get Defold to log the full stack trace?

**Comment by dossy** [comment] 2018-04-28 16:38
Okay, I realized I was totally using `coxpcall.lua` wrong.  Changing the naive `require` and replacing with the following seems to work on my iOS device, now:

```
if _VERSION == "Lua 5.1" and not jit then -- obsolete: only for Lua 5.1 compatibility
	local coxpcall = require "coxpcall"
	pcall = coxpcall.pcall
end
```

Going to do more testing ... but this looks promising!

**Comment by dossy** [comment] 2018-04-28 22:11
Quick update: Yup, this did the trick - almost.  This is what I ended up using in my actual project and it seems to work as expected:

```
if _VERSION == "Lua 5.1" and not jit then -- obsolete: only for Lua 5.1 compatibility
    local coxpcall = require "modules.coxpcall"

    pcall = coxpcall.pcall
    xpcall = coxpcall.xpcall
    running = coxpcall.running
end
```

**Comment by endel** [comment] 2018-04-28 22:38
Thanks a lot for sharing @dossy, and thanks @britzl for helping out! ❤️  I believe this should be documented on both [defold-websockets](https://github.com/britzl/defold-websocket) and [colyseus-defold](https://github.com/gamestdio/colyseus-defold/), isn't it?

I've never tried to deploy this on iOS, that's why I couldn't help. Tested only on Android here.

**Comment by britzl** [comment] 2018-04-29 06:36
@dossy Ah, sorry, the last time I used coxpcall it did the replacement automatically and immediately when the module was required. I see now that the behaviour has changed and you need to do the change manually.

@endel Yes, I'll make sure to document this. I completely forgot about it. I'll even include coxpcall in defold-websockets.

**Comment by britzl** [comment] 2018-04-29 06:50
I've released a new version of defold-websockets that handles this internally using coxpcall.

https://github.com/britzl/defold-websocket/blob/master/websocket/client_async.lua#L5-L9

**Comment by endel** [comment] 2018-05-15 21:29
I'm closing this issue since it seems to be resolved!

Some important discussion about IPv6 on iOS can be found on this thread: https://forum.defold.com/t/colyseus-multiplayer-game-client-server/17101/12

**Comment by britzl** [comment] 2018-05-16 04:23
Defold-Websocket has been upgraded to include the IPv6 connect code mentioned in the comment above. https://github.com/britzl/defold-websocket/blob/master/websocket/client_async.lua#L50-L74

**Comment by endel** [comment] 2018-06-15 03:33
Hey @britzl @dossy, is this really solved? 

@dossy have you managed to get rid of this error?

This is the first time I'm deploying a Defold app on iOS and I'm having exactly the same issue.

**Comment by britzl** [comment] 2018-06-15 04:46
Umm, I now realise that I have flipped the Vanilla Lua 5.1 check:

```
local VANILLA_LUA51 = _VERSION == "Lua 5.1" and not jit
local pcall = VANILLA_LUA51 and pcall or coxpcall.pcall
local corunning = VANILLA_LUA51 and coroutine.running or coxpcall.running
```

It should be the other way around:

```
local VANILLA_LUA51 = _VERSION == "Lua 5.1" and not jit
local pcall = VANILLA_LUA51 and coxpcall.pcall or pcall
local corunning = VANILLA_LUA51 and coxpcall.running or coroutine.running
```

Can you please try this and verify if it's working?

**Closed** 2018-06-15 14:13 UTC
